### ISSUE TITLE
Repositorio por defecto para la creación de registros de metadatos apunta a ruta inexistente

### ISSUE THREAD

**Issue by ghost** [miguelb15/unizar-vv-catmdedit#1]
El repositorio por defecto para la creación de registros de metadatos, descrito
en el fichero «catmdedit/repository/sources/metadata.rdf», apunta a una ruta inexistente
(«E:\workspacesEclipse\workspace\catmdeditOpenSource\CatMDEditOpenSource\
repository\metadata»).
/cc @miguelb15 @sergiocostamoreno

**Comment by miguelb15** [comment]
Se trata de un defecto antiguo ya corregido
