### ISSUE TITLE
Comprobación de Menú Ayuda

### ISSUE THREAD

**Issue by ghost** [miguelb15/unizar-vv-catmdedit#3]
Se lanza en Internet Explorer, buscador desactualizado. "Acerca de" versión de 2014. En UBUNTU no muestra el manual de usuario.

**Comment by miguel-latre** [comment]
Faltaría añadir la etiqueta _«wontfix»_, puesto que sin ella, se da a entender que el defecto se ha cerrado por haber sido corregido.
