### ISSUE TITLE
Comprobar el funcionamiento del visor de datos

### ISSUE THREAD

**Issue by ghost** [miguelb15/unizar-vv-catmdedit#4]
Seleccionando la opción abrir recurso muestra que no existe el fichero y no se abre.
En UBUNTU, mediante el boton “abrir recurso” no lo abre ni muestra que no lo puede abrir.

**Comment by miguelb15** [comment]
Duplicado

**Comment by miguel-latre** [comment]
Al cerrar como duplicado, es aconsejable indicar la incidencia duplicada (por ejemplo, #3).
